name: barber_shop_app
description: A beautiful barber shop booking application.

publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.5
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.1.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/